version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: simplebankdb
      POSTGRES_USER: simplebankuser
      POSTGRES_PASSWORD: simplebankpass
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dspring.datasource.url=jdbc:postgresql://db:5432/simplebankdb -Dspring.datasource.username=simplebankuser -Dspring.datasource.password=simplebankpass"
    depends_on:
      - db
    restart: always

volumes:
  dbdata:
